### ISSUE TITLE
--coverage fails the tests

### ISSUE THREAD

**Issue by HJZzzzz** [storybookjs/addon-coverage#14]
### Describe the bug

Tests are passed by default, but after runing the --coverage command, it throw error: 

![Screenshot 2022-12-07 at 2 15 34 PM](https://user-images.githubusercontent.com/44113416/206102841-3ee0a8f0-a9f4-4995-be5d-948b4712773e.png)

### Steps to reproduce the behavior

1.   run yarn test-storybook --coverage

### Screenshots and/or logs

Here are the settings in main.js

![Screenshot 2022-12-07 at 2 17 41 PM](https://user-images.githubusercontent.com/44113416/206103196-4bd70de2-dcd9-4df8-a496-fcb84ea02c7c.png)

**Comment by Lory1990** [comment]
Same problem here

**Comment by yannbf** [comment]
Hey folks, I believe this problem was fixed in 0.0.8, please try it out and feel free to reopen this in case you have any issues. Thank you!
