### ISSUE TITLE
[Bug] using storybook-addon-swc breaks this addon

### ISSUE THREAD

**Issue by Djiit** [storybookjs/addon-coverage#17]
### Describe the bug

When using `storybook-addon-swc`, this addons complains about the code not being implemented.

### Steps to reproduce the behavior

1. Add https://storybook.js.org/addons/storybook-addon-swc to a project
2. Use this addon

### Expected behavior

Coverage works

### Screenshots and/or logs

All tests return:

```
   [Test runner] An error occurred when evaluating code coverage:
             The code in this story is not instrumented, which means the coverage setup is likely not correct.
             More info: https://github.com/storybookjs/test-runner#setting-up-code-coverage
```

### Environment

 - OS: MacOS and Linux
 - Node.js version: 18.X
 - NPM version: yarn 1.22.19

**Comment by taozhou-glean** [comment]
any update on this ? we are getting exact same errors

**Comment by sebaguozden** [comment]
@s8n11c can you help me with this one #28?
