### ISSUE TITLE
nyc istanbul coverage ignore lines parsing hints not working 

### ISSUE THREAD

**Issue by anewstead** [storybookjs/addon-coverage#22]
### Describe the bug

code comments to hide lines from being included in coverage are not working.

### Steps to reproduce the behavior

can be seen from a clean install (storybook 7.0.12)

(package release below for reference)

```pnpm create vite```
- react
- typescript

```pnpm install```

```pnpm dlx storybook@latest init```
- eslint Y

```pnpm add --save-dev @storybook/test-runner```

```pnpm add --save-dev @storybook/addon-coverage```

package.json
```
"scripts": {
    "test-storybook": "test-storybook --coverage"
  }
```

.storybook/main.ts
```
addons: [
    '@storybook/addon-coverage',
  ],
```

terminal1: ```pnpm storybook```

terminal2: ```pnpm test-storybook```

nyc not installed!

```pnpm add --save-dev nyc```

update to latest testing library

```pnpm add --save-dev @storybook/testing-library@0.1.0```

**rerun test**

coverage shows Page.tsx uncovered line 17

add parsing hint at line 17 (pushes code to line 18)
```
/* istanbul ignore next */
```

**rerun test**

coverage shows Page.tsx uncovered line 18-19

move comment so line is now:
```
onLogin={
          /* istanbul ignore next */
          () => setUser({ name: "Jane Doe" })
        }
```

**rerun test**

coverage shows Page.tsx uncovered line 19

### Expected behavior

It should remove/ hide the line of code from coverage report

### Screenshots and/or logs

-

### Environment

 - OS: mac 13.3.1
 - Node.js version: 18.16.0
 - NPM version: 9.5.1 (pnpm 8.5.1)
 - Browser (if applicable): [e.g. chrome, safari]
 - Browser version (if applicable): [e.g. 22]
 - Device (if applicable): [e.g. iPhone6]

### Additional context

```
  "devDependencies": {
    "@storybook/addon-coverage": "^0.0.8",
    "@storybook/addon-essentials": "^7.0.12",
    "@storybook/addon-interactions": "^7.0.12",
    "@storybook/addon-links": "^7.0.12",
    "@storybook/blocks": "^7.0.12",
    "@storybook/react": "^7.0.12",
    "@storybook/react-vite": "^7.0.12",
    "@storybook/test-runner": "^0.10.0",
    "@storybook/testing-library": "^0.1.0",
    "@types/react": "^18.0.28",
    "@types/react-dom": "^18.0.11",
    "@typescript-eslint/eslint-plugin": "^5.57.1",
    "@typescript-eslint/parser": "^5.57.1",
    "@vitejs/plugin-react": "^4.0.0",
    "eslint": "^8.38.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.3.4",
    "eslint-plugin-storybook": "^0.6.12",
    "nyc": "^15.1.0",
    "prop-types": "^15.8.1",
    "storybook": "^7.0.12",
    "typescript": "^5.0.2",
    "vite": "^4.3.2"
  }
```
-

**Comment by TannerW** [comment]
Ran into this today as well. So +1 from me

**Comment by anewstead** [comment]
looks like this is related to comments being removed when typescript is transpiled in vite / esbuild.  
heres the workaround:  

```diff
-/* istanbul ignore if */
+/* istanbul ignore if -- @preserve */
if (condition) {
```

thanks to this thread:  
[https://github.com/vitest-dev/vitest/issues/2021#issuecomment-1242909898](https://github.com/vitest-dev/vitest/issues/2021#issuecomment-1242909898)
