### ISSUE TITLE
[Question] Make tests fail if coverage not met

### ISSUE THREAD

**Issue by luciob** [storybookjs/addon-coverage#24]
Hello, I've recently started using Storybook built in `test-runner` in combo with `addon-coverage`.

I was wondering if there's a way to define some threshold percentage and eventually make tests fail if these thresholds are not met. In Jest this can be achieved defining `coverageThreshold` as follows:

```
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
```

I've tried using the `options.istanbul` object of `addon-coverage` in `main.js` without success (https://storybook.js.org/docs/react/writing-tests/test-coverage#configure)

How can I achieve something similar with `test-runner` and `addon-coverage`?
Thank you

**Comment by gilbarbara** [comment]
Hey @luciob 

Try adding a `.nycrc` file to your project with these lines:

```json
{
  "all": true,
  "check-coverage": true,
  "branches": 50,
  "functions": 70,
  "lines": 70,
  "statements": 70
}
```

**Comment by luciob** [comment]
Thanks @gilbarbara that worked just fine 👍
