### ISSUE TITLE
[Bug] Doesn't work when Storybook is built with the new --test flag

### ISSUE THREAD

**Issue by otaviomad** [storybookjs/addon-coverage#31]
### Describe the bug

Storybook 7.6 introduced a new --test flag for building Storybook with less of the fluff that is not needed for testing environments.
When you try to run test-storybook with --coverage on a storybook that was built with --test, I get the following error:
```
The code in this story is not instrumented, which means the coverage setup is likely not correct.
```

### Steps to reproduce the behavior

1. Build a Storybook with --test
2. Run test-storybook on that with --coverage
3. Rebuild the same Storybook without --test
4. Test storybook passes

### Expected behavior

I believe that the istanbul plugin is not being properly injected when --test is enabled. I don't get the `[addon-coverage] Adding istanbul plugin to Vite config` message when I use it. The coverage should work when --test is enabled.

**Comment by vicrep** [comment]
Experiencing the same issue here.

Did a little digging and it _seems_ that the coverage add-on is disabled by default if not overridden? https://github.com/storybookjs/storybook/blob/00124ed94f397d2d6c0a9fa8bbad823cfa1b0ab9/code/lib/core-server/src/presets/common-override-preset.ts#L41

**Comment by jonniebigodes** [comment]
@otaviomad, thanks for reporting this, and also @vicrep appreciate your assistance on this 🙏 . So that you're aware, I've pushed a pull request here and will push another into the official documentation to address this until we have a proper fix. 

Hope you all have a great day.

Stay safe
