### ISSUE TITLE
The type of rawSourceMap is string，But the type defined by the code is object

### ISSUE THREAD

**Issue by hkaikai** [storybookjs/addon-coverage#32]
https://github.com/storybookjs/addon-coverage/blob/aacb3fb382c368675a6015a446b9caa3b8cf5f09/src/loader/webpack5-istanbul-loader.ts#L28

<img width="1255" alt="image" src="https://github.com/storybookjs/addon-coverage/assets/19343340/3071de8e-e183-4647-ace0-31e3ceabf44e">

Causes downstream code to report errors
<img width="1316" alt="image" src="https://github.com/storybookjs/addon-coverage/assets/19343340/d9721f07-6838-4c62-8990-d51f10234e15">

**Comment by hkaikai** [comment]
My configuration is：
```javascript
// .storybook/main.js

/* eslint-disable storybook/no-uninstalled-addons */
/** @type { import('@storybook/vue-webpack5').StorybookConfig } */
import cssConfig from '../build/css.config.json';

const config = {
  stories: ['../src/**/*.mdx', '../src/**/*.stories.@(js|jsx|mjs|ts|tsx)'],
  addons: [
    '@storybook/addon-links', // https://storybook.js.org/addons/@storybook/addon-links/
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
    '@storybook/addon-docs',
    {
      name: '@storybook/addon-styling-webpack',
      options: {
        rules: [{
          test: /\.((c|sa|sc)ss)$/i,
          use: [
            'style-loader',
            ...cssConfig,
          ],
        }],
      },
    },
    '@storybook/addon-coverage',
  ],
  framework: {
    name: '@storybook/vue-webpack5',
    options: { builder: { useSWC: true } },
  },
  docs: {
    autodocs: true,
  },
};
export default config;

```

```
// devDependencies

    "@storybook/addon-coverage": "^1.0.0",
    "@storybook/addon-essentials": "^7.6.2",
    "@storybook/addon-interactions": "^7.6.2",
    "@storybook/addon-links": "^7.6.2",
    "@storybook/addon-styling-webpack": "^0.0.5",
    "@storybook/blocks": "^7.6.2",
    "@storybook/test": "^7.6.2",
    "@storybook/test-runner": "^0.16.0",
    "@storybook/vue": "^7.6.2",
    "@storybook/vue-webpack5": "^7.6.2",
    "storybook": "^7.6.2",
```

**Comment by hkaikai** [comment]
https://github.com/storybookjs/storybook/pull/24805?ref=storybookblog.ghost.io

Problems caused after useSWC is turned on

**Comment by dbudwin** [comment]
I am also encountering this same issue using Storybook v8.0.5.  @yannbf or @jonniebigodes any insight here?

**Comment by yannbf** [comment]
Hey @dbudwin please let us know whether [v1.0.3](https://github.com/storybookjs/addon-coverage/releases/tag/v1.0.3)[v1.0.3](https://github.com/storybookjs/addon-coverage/releases/tag/v1.0.3) fixed your issues!

**Comment by dbudwin** [comment]
@yannbf I no longer get that error; however, I can't see my test coverage.  When it's done running this is all I see.  The `.nyc_output` directory gets deleted for some reason when it finishes running.

![image](https://github.com/storybookjs/addon-coverage/assets/15161181/e4924198-7169-42cf-ae01-c46005906def)

**Comment by dbudwin** [comment]
@yannbf thanks so much--works like a charm now!
