### ISSUE TITLE
[Feat] define coverage folder path

### ISSUE THREAD

**Issue by yann-combarnous** [storybookjs/addon-coverage#43]
By default, this plugin creates coverage report in the project root folder. 

For Nx and monorepos, the coverage folder is generally at the root of the Monorepo, so it would be convenient to have this option for Storybbok coverage as well.

Reference option in Vitest: https://vitest.dev/guide/coverage#changing-the-default-coverage-folder-location

**Comment by yann-combarnous** [comment]
My bad, this can be done with nycrc.

**Comment by cglango** [comment]
Can you post your solution please? Wondering the same thing.
