### ISSUE TITLE
[Bug] Regression parsing of string source maps

### ISSUE THREAD

**Issue by mschimk1** [storybookjs/addon-coverage#45]
### Describe the bug

A regression in v1.0.4 when loading source maps of type string in [webpack5 instanbul loader](https://github.com/storybookjs/addon-coverage/blob/main/src/loader/webpack5-istanbul-loader.ts#L28)

### Steps to reproduce the behavior

Build storybook stories with webpack5 configuration. E.g.,

```
storybook build --webpack-stats-json
```

@storybook/cli v7.6.19

info => Cleaning outputDir: /storybook-static
info => Loading presets
info => Building manager..
info => Manager built (1.92 s)
info => Building preview..
info => Copying static files: 
...
info Using SWC compiler
info Addon-docs: using MDX2
info => Using implicit CSS loaders
...
info => Using default Webpack5 setup

_The build fails with errors similar to the one below:_

Module build failed (from ../../node_modules/.pnpm/@storybook+addon-coverage@1.0.4/node_modules/@storybook/addon-coverage/dist/cjs/loader/webpack5-istanbul-loader.js):
**Error: .inputSourceMap must be a boolean, object, or undefined**
    at transformSync (<redacted>/node_modules/.pnpm/@babel+core@7.24.6/node_modules/@babel/core/lib/transform.js:42:76)
    at Instrumenter.instrumentSync (<redacted>/node_modules/.pnpm/istanbul-lib-instrument@6.0.2/node_modules/istanbul-lib-instrument/src/instrumenter.js:102:25)
    at Object._default (<redacted>/node_modules/.pnpm/@storybook+addon-coverage@1.0.4/node_modules/@storybook/addon-coverage/dist/cjs/loader/webpack5-istanbul-loader.js:36:29)

### Expected behavior

The string type source map should be parsed into an object which is then fed into the code instrumentation.

Please view the patch I have contributed https://github.com/storybookjs/addon-coverage/pull/44.

### Screenshots and/or logs

Please refer to sample error above

### Environment

 - OS: MacOS Sonoma v14.5
 - Node.js version: v20.12.2
 - NPM version: pnpm 9.4.0
 - Browser (if applicable): N/A
 - Browser version (if applicable): N/A
 - Device (if applicable): N/A

### Additional context

A very similar issue was previously reported here https://github.com/storybookjs/addon-coverage/issues/32, and fixed in https://github.com/storybookjs/addon-coverage/pull/33.

However, it was reintroduced as part of [Fix sourcemap generation for Webpack5 projects](https://github.com/storybookjs/addon-coverage/pull/42/files#diff-bf8912f263fb99ddb75893bcc11ed6800288dfd57de2fdd67337b8b74442044cR28).

**Comment by gpincheiraa** [comment]
any news about this issue?

**Comment by yannbf** [comment]
This issue is solved in [v1.0.5](https://github.com/storybookjs/addon-coverage/releases/tag/v1.0.5). Thanks for the fix, @mschimk1 !
