### ISSUE TITLE
Hint: merge coverage with Jest

### ISSUE THREAD

**Issue by czabaj** [storybookjs/addon-coverage#9]
Thank you for the addon, it came to me just at the right time when I configured coverage reports for my recent codebase.

I spend the last few hours figuring out how to merge the coverage report from Storybook with the coverage report from Jest. I find the Storybook interaction testing convenient for React components and I don't want to duplicate the interaction tests in Jest, so when I run coverage for the Jest and then a Storybook, I obtain two coverages for the same codebase and I needed to merge them somehow to measure, how much is my codebase covered in total.

After fiddling with instanbul/nyc, which leads nowhere, I find out [istanbul-merge](https://github.com/ljharb/istanbul-merge#readme) package. When you have two or more JSON reports, it can merge them to give you a holistic overview.

The Storybook already produces JSON reports, so I only [configured the Jest to use `json` reporter](https://jestjs.io/docs/configuration#coveragereporters-arraystring--string-options) and then I merged the two reports together with

```sh
npx istanbul-merge --out coverage/coverage-merged.json coverage/storybook/coverage-storybook.json coverage/coverage-final.json
```

which gives you a merged json report. You can then covert it to the LCOV report with

```sh
npx nyc report -t coverage --reporter=lcov --reporter=text
```

**Comment by yannbf** [comment]
Thanks for the nice writeup @czabaj! There is actually a section in the Storybook test-runner repo that explains how to do that:
https://github.com/storybookjs/test-runner#3---merging-code-coverage-with-coverage-from-other-tools

The purpose of the addon is to instrument the code, but what actually reports coverage is the test-runner. Please let me know if there's a way to improve communication so others don't have to spend time figuring this out, thank you!
